#! /usr/bin/env python

from commandr import Run
from reduc.stopspam.postqueue import postqueue, queue_by_senders, \
    queue_by_messages, rmqueue
from reduc.stopspam.zimbra import zimbra_suspend, zimbra_reactivate, \
    zimbra_status
from reduc.stopspam.maillog import maillog_by_qmgr, maillog_by_sasl
from reduc.stopspam.server import serve


if __name__ == '__main__':
    Run()
